### ISSUE TITLE
Probleme d'import RE avec xtense

### ISSUE THREAD

**Issue by klibr-insain** [OGSteam/mod-xtense#12]
Bonjour,

Lors d'import de rapport d'espionnage, xtense importe la défense planete sur la lune alors qu'il n'y en a pas.

Step 1 : spy colo
Step 2 : spy lune

Lors de l'import planete : RE ok
Lors de l'import lune : RE ok

Si réimport planete RE lune pas ok

Aucun problème visible dans le mode debug

**Comment by Roms0406** [comment]
Bonsoir,

Non pas qu'il ne faille pas regarder cela de plus près, mais je veux juste préciser que je n'ai pas été en mesure de reproduire ce bug sans pour autant identifier d'erreur de configuration ou autres du côté d'Insain.
Le problème reste permanent chez lui malgré tout ce que l'on a tenté ...

**Comment by klibr-insain** [comment]
Hello Messieurs,

J'ai installé un carto dans sa dernière version pour testé (le bug était présent dans la 3.3.4) et il est également présent en 3.3.5.

Ce bug est vraiment gênant car on peut pas se fier à un RE importé correctement.

Je suis conscient d'être potentiellement le seul, et vous avez certainement d'autre priorité également ;) mais pourriez-vous à l'occasion m'aidé ?

Qui plus est, je peux vous proposé de faire un vocale sur discord, avec partage d'écran, afin de vous aidé à le reproduire, le voir de vous même, repartir d'une carto totalement vierge, ce genre de chose et ainsi avancé sur ce problème.

En vous remerciant grandement.
Insain

**Comment by darknoon29** [comment]
@klibr-insain J'ai reuv l'import du RE. Tu pourras revérifier avec les versions Xtense Mod et Extension >= 2.9.0 ? Merci pour ton aide :-)
