### ISSUE TITLE
Recuperation du token 

### ISSUE THREAD

**Issue by machine62** [OGSteam/mod-xtense#14]
Ogspy 3.3.5
xtense derniere version, 

du coup les infos ne remontent pas.
pour info j'ai un autre ogspy en local qui fonctionne parfaitement

![image](https://user-images.githubusercontent.com/28401480/56846171-f46dd800-68cb-11e9-8867-3f3c3cf16e70.png)

**Comment by darknoon29** [comment]
Comme si en base tu avais 2 tokens pour un utilisateur

**Comment by machine62** [comment]
oui c'est marrant  non :)

**Comment by darknoon29** [comment]
Ou que le filtre sur l'utilisateur ne fonctionne pas

**Comment by machine62** [comment]
Je vais réinstaller cet ogspy ....

on verra bien

**Comment by darknoon29** [comment]
Je viens de retester et tout va bien ;-) Je te laisse me confirmer le soucis.

**Comment by machine62** [comment]
il faut que je me motive a remettre les fichiers d'origine ...
Je ferme pour le moment, j'ouvrirai si plus d'info
