### ISSUE TITLE
renouvellement token

### ISSUE THREAD

**Issue by machine62** [OGSteam/mod-xtense#15]
A priori impossible :

![image](https://user-images.githubusercontent.com/28401480/56846184-37c84680-68cc-11e9-99fc-225cd24145f7.png)

**Comment by darknoon29** [comment]
J'ai déjà corrigé ça normalement. C'était un bug de l'alpha 🤔

**Comment by darknoon29** [comment]
C'était un bug OGSpy

**Comment by machine62** [comment]
c interessant vu que je suis en derniere version ...

je crois que je vais refaire une installation propre

**Comment by darknoon29** [comment]
C'était un mauvais copier coller. Le  insert into Oui Mais pas le update into 😅
