### ISSUE TITLE
Remontée RC et recyclage - Ogame v6.3.5

### ISSUE THREAD

**Issue by Itori** [OGSteam/mod-xtense#2]
Suite à la MAJ 6.3.5 d'Ogame, le format des rapports de combat ne sont plus compatibles (voir OGSteam/tool-xtense-web-extension#1)

- [x] Intrégration du rapport de combat
- [x] Intégration des rounds
- [x] Intégration des flottes

**Comment by darknoon29** [comment]
Hello, Tu as eu un peu de temps pour avancer sur le sujet ?

**Comment by darknoon29** [comment]
`"Xtense says : sending toolbar_version=2.7.4&toolbar_type=GM-FF&mod_min_version=2.7.2&user=darknoon&password=b1df4ba4ef92f347096734a47c731317&univers=https://s801-en.ogame.gameforge.com&type=rc&json={"event_time":"2017-03-31T08:09:58+01:00","event_timestamp":1490944198,"defenderPlanetId":"33712207","coordinates":{"galaxy":"4","system":"406","position":"10","planetType":"1"},"attacker":{"2231569":{"ownerName":"muli","ownerID":"109060","ownerCoordinates":"4:430:10","ownerPlanetType":"1","ownerHomePlanet":"Homeworld","planetId":"33716555","fleetID":"2231569","armorPercentage":20,"weaponPercentage":20,"shieldPercentage":0,"shipDetails":{"203":{"armor":1440,"weapon":6,"shield":25,"count":33},"205":{"armor":1200,"weapon":180,"shield":25,"count":2}}}},"defender":[{"ownerName":"darknoon","ownerID":"108956","ownerCoordinates":"4:406:10","ownerPlanetType":"1","ownerHomePlanet":"Homeworld","planetId":"33712207","fleetID":0,"ownerAlliance":"Itori","ownerAllianceTag":"Ito","armorPercentage":20,"weaponPercentage":20,"shieldPercentage":30,"shipDetails":[]}],"combatRounds":[{"statistics":null,"attackerLosses":null,"defenderLosses":null,"attackerShips":{"2231569":{"203":33,"205":2}},"defender":[],"defenderShips":[[]]}],"statistic":{"lostUnitsAttacker":0,"lostUnitsDefender":0},"result":"attacker","debris":{"metal":0,"crystal":0,"darkMatter":0},"loot":{"metal":418939,"crystal":124949,"deuterium":111433},"repairedDefense":[],"moon":{"genesis":false,"chance":0,"size":0,"exists":0},"honor":{"honorableAttacker":false,"attackerHonorPoints":0,"honorableDefender":true,"defenderHonorPoints":0,"isCombatWithoutHonor":false},"tacticalRetreat":{"active":0,"attacker":false,"supremacy":119000},"lootPercentage":50,"debugData":{"combatmicrostart":1490944198.5219,"combatmicroend":1490944198.5303,"planet_metal_start":418939,"planet_crystal_start":124949,"planet_deuterium_start":111433,"planet_metal_end":446061,"planet_crystal_end":130051,"planet_deuterium_end":113349.51666667},"hashcode":"1c04cff10c2ee0ba1cd323f1eefdd4f16e04c892","combatId":"501858","spioReportPictures":null,"attackerJSON":{"member":{"2231569":{"ownerName":"muli","ownerID":"109060","ownerCoordinates":"4:430:10","ownerPlanetType":"1","ownerHomePlanet":"Homeworld","planetId":"33716555","fleetID":"2231569","armorPercentage":20,"weaponPercentage":20,"shieldPercentage":0,"shipDetails":{"203":{"armor":1440,"weapon":6,"shield":25,"count":33},"205":{"armor":1200,"weapon":180,"shield":25,"count":2}}}},"combatRounds":[{"lossesInThisRound":null,"statistic":{"hits":0,"absorbedDamage":0,"fullStrength":0},"losses":null,"ships":{"2231569":{"203":33,"205":2}}}]},"defenderJSON":{"member":[{"ownerName":"darknoon","ownerID":"108956","ownerCoordinates":"4:406:10","ownerPlanetType":"1","ownerHomePlanet":"Homeworld","planetId":"33712207","fleetID":0,"ownerAlliance":"Itori","ownerAllianceTag":"Ito","armorPercentage":20,"weaponPercentage":20,"shieldPercentage":30,"shipDetails":[]}],"combatRounds":[{"lossesInThisRound":null,"statistic":{"hits":0,"absorbedDamage":0,"fullStrength":0},"losses":null,"ships":[[]]}]}}&ogapilnk=cr-en-801-1c04cff10c2ee0ba1cd323f1eefdd4f16e04c892 to http://host.darkcity.fr/~darknoon/ogspy/mod/xtense/xtense.php from https://s801-en.ogame.gameforge.com"`

**Comment by darknoon29** [comment]
RC à un tour

**Comment by Itori** [comment]
La plupart des points sont corrigés, nécessite maintenant d'avoir un RC avec défense groupée.

**Comment by darknoon29** [comment]
Pas de remontées depuis : tout va bien :-)
