### ISSUE TITLE
Erreur PHP lors de l'installation

### ISSUE THREAD

**Issue by pitch314** [OGSteam/mod-xtense#35]
[PHP-ERROR] 2 - require_once(mod//includes/config.php): failed to open stream: No such file or directory ; Fichier: /app/mod/xtense/install.php ; Ligne: 25

[PHP-ERROR] 8 - Undefined variable: pub_directory ; Fichier: /app/mod/xtense/install.php ; Ligne: 10
=>Il faut d'abords vérifier avec isset avant de l'utiliser.

**Comment by darknoon29** [comment]
@pitch314 Je le mettrais même en dur. Le nom du répertoire n'est pas censé changer
