### ISSUE TITLE
incompatibiliter xtense vs xtense

### ISSUE THREAD

**Issue by marsnameless** [OGSteam/mod-xtense#6]
le module xtense est incompatible (undefined ms)(ogspy)la version du mod xtense sur le serveur est incompatible avec votre pluing.merci de mettre a jour votre module xtense

bon bien tus est la noter que j'ai tous installé cette nuit avec les derniere version disponible j'ai fais les mise a jour dans ogspy desinstaller est reinstallé le module firefox xtense et de meme dans le serveur ogspy que dois-je faire maintenant

**Comment by darknoon29** [comment]
Bonjour,

Peux tu me donner les liens de téléchargement que tu as utilisé ?

Merci !

**Comment by marsnameless** [comment]
bon  le probleme est regler j ai du desinstallé le syteme de mise a jour et le reinstallé sans le mettre a jour et j'ai pu mettre xtense a jour...donc le probleme vien de la mise a jour du module d auto mise a jour

**Comment by darknoon29** [comment]
Je n'ai pas bien compris. Du coup tu as la dernière version ? 2.7.3 côté OGSpy ?
En tous cas la mise à jour manuelle est en deux étapes : 1 - Copie des fichiers et 2- Mise à jour dans la partie administration.

Ceci est automatique par contre avec autoupdate.

Content du coup que ton soucis soit résolu ;-)

**Comment by marsnameless** [comment]
oui tous est fonctionnel mais je vais quand meme tenter de expliquer quand jai installé les module :xtense et auto mise a jour je suis ensuit allé dans l auto mise a jour j avais une mise a jour sur disponible sur ogspy,auto mise a jour et xtense j ai mis a jour le ogspy tous cest bien passer jai enchainer avec auto mise a jour et la la mise a jour de xtense a disparu j ai donc desinstaller l auto mise a jour et je les reinstaller sans faire la mise a jour se qui a fais reapparaitre la mise a jour de xtense que jai fais et mon probleme a ete resolue
