### ISSUE TITLE
Bug Xtense et AGO

### ISSUE THREAD

**Issue by nicolas31d** [OGSteam/mod-xtense#7]
Bonjour, 

Lorsque Xtense est "Actif" l'affichage des coordonées d'un joueur bug sur AGO:

![image](https://user-images.githubusercontent.com/38253690/38562382-b91a9ad6-3cda-11e8-98ae-c0b6fe6b8079.png)

Lorsque l'on désactive Xtense dans le menu Extension le probleme est résolu

Pourriez vous svp corriger le probleme ? 

Merci d'avance; 

Nicolas

**Comment by darknoon29** [comment]
Je vais regarder en espérant que ce ne soit pas un soucis côté AGO ;-)

**Comment by darknoon29** [comment]
Kamino closed and cloned this issue to OGSteam/tool-xtense-web-extension
